In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Importing the dataset
dataset = pd.read_csv("/Users/Asad/Desktop/Personal/Codes/Machine Learning A-Z /Part 7 - Natural Language Processing/Section 36 - Natural Language Processing/Restaurant_Reviews.tsv",
                     delimiter = "\t", quoting = 3)

In [45]:
# Cleaning Texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = [] # Including all the reviews
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower() # converting all the letters to the lowercase
    review = review.split() # splitting the strings to list
# review = [word for word in review if not word in set(stopwords.words('english'))] # reading each list and excluding the stopwords
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] # Stemming the root i.e here loved is chnaged to love
    review = ' '.join(review) # joining the list back to a string 
    corpus.append(review)

[nltk_data] Downloading package stopwords to /Users/Asad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [46]:
# Creating the Bag of Word model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values #Dependent Variable(Outcome of the review): 1 is postive review and 0 is negative. 

In [47]:
# Applying the Naive Bayes # Splitting into Training and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state= 0)

In [48]:
# Fitting Naive Bayes to the training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [49]:
# Predicting the Test Results
y_pred = classifier.predict(X_test)

In [50]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 42],
       [12, 91]])

In [66]:
print('Accuracy',(55+91)/200)
print('Precision', 91/(91+42))
print('Recall', 91/(91+12))

Accuracy 0.73
Precision 0.6842105263157895
Recall 0.883495145631068


In [53]:
# Applying Random Forest
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state =0)
classifier2.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [54]:
#Predicting Test Results
y_pred2 = classifier2.predict(X_test)

In [55]:
cm2 = confusion_matrix(y_test, y_pred2)
cm2

array([[87, 10],
       [46, 57]])

In [67]:
print('Accuracy',(87+57)/200)
print('Precision', 57/(57+10))
print('Recall', 57/(57+46))

Accuracy 0.72
Precision 0.8507462686567164
Recall 0.5533980582524272


In [56]:
# Applying Decision Tree
from sklearn.tree import DecisionTreeClassifier
classifier3 = DecisionTreeClassifier(criterion = 'entropy', random_state= 0)
classifier3.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [57]:
#Predicting Test Results
y_pred3 = classifier3.predict(X_test)

In [58]:
# Confusion Matrix
cm3 = confusion_matrix(y_test, y_pred3)
cm3

array([[74, 23],
       [35, 68]])

In [68]:
print('Accuracy', (74+68)/200)
print('Precision', 68/(68+23))
print('Recall', 68/(68+35))

Accuracy 0.71
Precision 0.7472527472527473
Recall 0.6601941747572816


In [70]:
# Applying SVM 
from sklearn.svm import SVC
classifier4 = SVC(kernel = 'linear', random_state = 0)
classifier4.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [71]:
# Predicting the test results
y_pred4 = classifier4.predict(X_test)

In [73]:
#Confusion matrix
cm4 = confusion_matrix(y_test, y_pred4)
cm4

array([[74, 23],
       [33, 70]])

In [74]:
print('Accuracy', (74+70)/200)
print('Precision', 70/(70+23))
print('Recall', 70/(70+33))

Accuracy 0.72
Precision 0.7526881720430108
Recall 0.6796116504854369
